import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { chromium, type Browser, type BrowserContext } from "playwright-core";
import {
  BASE_URL,
  cleanupE2EUser,
  registerBrowserUser,
  SESSION_COOKIE,
  startStack,
  stopStack,
  type E2EStack,
  type RegisteredBrowserUser,
} from "./support/image-harness";

/**
 * Real browser proof that a generated image feeds the visual engine.
 *
 * A graphic is produced in the CP17 workspace, its `generated:` reference is
 * pasted into a visual composition as a MEDIA layer, and the CP15 render worker
 * is asked to build an MP4 from it. The MP4 must exist and start with an ftyp
 * box, which can only happen if the resolver read the stored image bytes.
 */

type Services = typeof import("../../src/infrastructure/services");

let stack: E2EStack;
let services: Services;
let user: RegisteredBrowserUser;
let browser: Browser;
let context: BrowserContext;
const projectIds: string[] = [];
let email = "";

beforeAll(async () => {
  stack = await startStack({ withRenderWorker: true });
  if (!stack.reachable || !stack.available) return;

  services = await import("../../src/infrastructure/services");

  email = `cp17-to-visual-${Date.now()}@test.local`;
  user = await registerBrowserUser(email);

  browser = await chromium.launch({
    executablePath: stack.executablePath,
    args: ["--no-sandbox"],
  });
  context = await browser.newContext();
  await context.addCookies([
    {
      name: SESSION_COOKIE,
      value: user.cookieValue,
      url: BASE_URL,
    },
  ]);
});

afterAll(async () => {
  if (browser) await browser.close();
  stopStack(stack);
  if (user) await cleanupE2EUser(email, user.workspaceId, projectIds);
});

describe("generated image to visual render end to end", () => {
  it("is runnable in this environment", (testContext) => {
    if (!stack.reachable || !stack.available) {
      testContext.skip();
      return;
    }
    expect(stack.executablePath).toBeTruthy();
  });

  it("renders an MP4 whose MEDIA layer is a generated image", async (testContext) => {
    if (!stack.reachable || !stack.available) {
      testContext.skip();
      return;
    }

    const project = await services.projectService.createForWorkspace(
      user.workspaceId,
      { name: "CP17 E2E to visual" },
      user.userId,
    );
    projectIds.push(project.id);

    // 1. Generate a real image in the CP17 workspace.
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/projects/${project.id}`, {
      waitUntil: "domcontentloaded",
    });
    await page
      .getByTestId("image-generation-workspace")
      .waitFor({ state: "visible", timeout: 30_000 });

    await page.getByTestId("image-prompt-input").fill("Hero for the render");
    await page.getByTestId("generate-image-button").click();

    await expect
      .poll(
        async () => {
          const item = page.getByTestId("generated-image-item").first();
          return (await item.count()) > 0;
        },
        { timeout: 90_000, interval: 500 },
      )
      .toBe(true);
    await page.getByTestId("generated-image-item").first().click();
    await page
      .getByTestId("generated-asset-ref")
      .waitFor({ state: "visible", timeout: 15_000 });
    const generatedRef = await page.getByTestId("generated-asset-ref").inputValue();
    expect(generatedRef).toMatch(/^generated:/);
    await page.close();

    // 2. Put the generated bytes behind a MEDIA layer.
    const composition = await services.visualCompositionService.createComposition({
      projectId: project.id,
      userId: user.userId,
      name: "Generated media render",
      width: 320,
      height: 240,
      frameRate: 12,
      durationMs: 1000,
    });

    const visualPage = await context.newPage();
    const consoleErrors: string[] = [];
    visualPage.on("console", (message) => {
      if (message.type() === "error") consoleErrors.push(message.text());
    });

    await visualPage.goto(
      `${BASE_URL}/projects/${project.id}/visual/${composition.id}`,
      { waitUntil: "domcontentloaded" },
    );
    await visualPage
      .getByTestId("media-ref-input")
      .waitFor({ state: "visible", timeout: 30_000 });

    await visualPage.getByTestId("media-ref-input").fill(generatedRef);
    await visualPage.getByTestId("add-media-layer").click();

    await expect
      .poll(async () => visualPage.getByTestId("layer-list-item").count(), {
        timeout: 20_000,
        interval: 500,
      })
      .toBe(1);

    // 3. Render and fetch the artifact.
    await visualPage.getByTestId("render-video").click();
    await expect
      .poll(
        async () => visualPage.getByTestId("render-status").textContent(),
        { timeout: 90_000, interval: 1_000 },
      )
      .toContain("SUCCEEDED");

    const download = visualPage.getByTestId("render-download");
    await download.waitFor({ state: "visible", timeout: 15_000 });
    const href = await download.getAttribute("href");
    expect(href).toBeTruthy();

    const streamed = await context.request.get(`${BASE_URL}${href}`);
    expect(streamed.status()).toBe(200);
    expect(streamed.headers()["content-type"]).toContain("video/mp4");
    const bytes = await streamed.body();
    expect(bytes.byteLength).toBeGreaterThan(0);
    expect(bytes.subarray(4, 8).toString("ascii")).toBe("ftyp");

    expect(consoleErrors).toEqual([]);
    await visualPage.close();
  }, 150_000);
});
