import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { resolveAssetRef } from "../../visual-motion-engine/integrations/capture-take";
import type { RenderAssetDependencies } from "../../video-rendering/assets/render-asset-resolver";
import { RenderAssetResolver } from "../../video-rendering/assets/render-asset-resolver";
import { generatedAssetRef } from "../assets/asset-reference";
import { ImageGenerationWorker } from "../generation-worker";
import type { LocalImageStorage } from "../storage/image-storage";
import {
  cleanupUser,
  createAnalyzedProject,
  loadImageTestContext,
  makeTempImageStorage,
  makeWorker,
  registerUser,
  type Orm,
  type Services,
} from "./helpers";

let services: Services;
let orm: Orm;
let worker: ImageGenerationWorker;
let storage: LocalImageStorage;
let cleanupStorage: () => Promise<void>;
let owner: Awaited<ReturnType<Services["authService"]["register"]>>;
let projectId: string;
let other: Awaited<ReturnType<Services["authService"]["register"]>>;
let otherProjectId: string;

let assetId: string;
let assetRef: string;
let originalBytes: Buffer;

async function drain(): Promise<void> {
  let worked = await worker.tick();
  while (worked) worked = await worker.tick();
}

beforeAll(async () => {
  const context = await loadImageTestContext();
  services = context.services;
  orm = context.orm;

  const temp = await makeTempImageStorage();
  storage = temp.storage;
  cleanupStorage = temp.cleanup;
  worker = makeWorker({ services, storage });

  const analyzed = await createAnalyzedProject(services);
  owner = analyzed.owner;
  projectId = analyzed.projectId;

  other = await registerUser(services, "cp17-gen-other");
  const otherProject = await services.projectService.createForWorkspace(
    other.workspace!.id,
    { name: "CP17 generated isolation" },
    other.user.id,
  );
  otherProjectId = otherProject.id;

  const job = await services.imageGenerationService.enqueue({
    projectId,
    requestedById: owner.user.id,
    templateType: "PRODUCT_HERO",
    prompt: "Layer me into a render",
    width: 360,
    height: 360,
  });
  await drain();

  const asset = await services.imageGenerationService.asset({
    projectId,
    jobId: job.id,
    userId: owner.user.id,
  });
  assetId = asset!.id;
  assetRef = generatedAssetRef(assetId);
  originalBytes = await readFile(storage.absolutePath(asset!.storageKey));
});

afterAll(async () => {
  if (owner) await cleanupUser(orm, owner, projectId);
  if (other) await cleanupUser(orm, other, otherProjectId);
  await cleanupStorage();
});

describe("generated: asset references", () => {
  it("resolves a generated reference to its real dimensions", async () => {
    const resolved = await resolveAssetRef(projectId, assetRef);
    expect(resolved.kind).toBe("generated");
    expect(resolved.id).toBe(assetId);
    expect(resolved.width).toBe(360);
    expect(resolved.height).toBe(360);
    expect(resolved.durationMs).toBeNull();
  });

  it("does not resolve another project's generated asset", async () => {
    await expect(resolveAssetRef(otherProjectId, assetRef)).rejects.toMatchObject(
      { status: 404 },
    );
  });

  it("stops resolving once the asset has been soft-deleted", async () => {
    const job = await services.imageGenerationService.enqueue({
      projectId,
      requestedById: owner.user.id,
      templateType: "QUOTE_CARD",
      prompt: "Temporary asset for deletion",
      width: 256,
      height: 256,
    });
    await drain();

    const doomed = await services.imageGenerationService.asset({
      projectId,
      jobId: job.id,
      userId: owner.user.id,
    });
    const doomedRef = generatedAssetRef(doomed!.id);

    await services.imageRepository.softDeleteAsset(
      projectId,
      doomed!.id,
      new Date().toISOString(),
    );

    await expect(resolveAssetRef(projectId, doomedRef)).rejects.toMatchObject({
      status: 404,
    });
  });
});

describe("RenderAssetResolver for generated images", () => {
  it("writes the generated bytes into the render work directory", async () => {
    const workDir = await mkdtemp(path.join(tmpdir(), "cp17-resolve-"));
    try {
      const resolver = new RenderAssetResolver({
        captures: {} as never,
        assets: {} as never,
        images: services.imageRepository,
        captureStorage: {} as never,
        imageStorage: storage,
        storage: {} as never,
        probe: async () => ({ width: 360, height: 360 }),
      } satisfies Partial<RenderAssetDependencies> as RenderAssetDependencies);

      const compiled = await resolver.resolve(projectId, assetRef, workDir, 0);
      expect(compiled.kind).toBe("image");
      expect(compiled.width).toBe(360);

      const written = await readFile(compiled.path);
      expect(written.equals(originalBytes)).toBe(true);
    } finally {
      await rm(workDir, { recursive: true, force: true });
    }
  });

  it("refuses a generated asset that belongs to another project", async () => {
    const workDir = await mkdtemp(path.join(tmpdir(), "cp17-resolve-"));
    try {
      const resolver = new RenderAssetResolver({
        captures: {} as never,
        assets: {} as never,
        images: services.imageRepository,
        captureStorage: {} as never,
        imageStorage: storage,
        storage: {} as never,
        probe: async () => ({ width: 360, height: 360 }),
      } satisfies Partial<RenderAssetDependencies> as RenderAssetDependencies);

      await expect(
        resolver.resolve(otherProjectId, assetRef, workDir, 0),
      ).rejects.toMatchObject({ code: "ASSET_NOT_FOUND" });
    } finally {
      await rm(workDir, { recursive: true, force: true });
    }
  });
});

describe("generated: references inside a visual composition", () => {
  it("accepts a MEDIA layer that points at a generated asset", async () => {
    const composition = await services.visualCompositionService.createComposition(
      {
        projectId,
        userId: owner.user.id,
        name: "Generated layer composition",
      },
    );

    const layer = await services.visualLayerService.addLayer({
      projectId,
      compositionId: composition.id,
      userId: owner.user.id,
      type: "MEDIA",
      assetRef,
    });

    expect(layer.assetRef).toBe(assetRef);
    expect(layer.type).toBe("MEDIA");
  });

  it("rejects a cross-project generated layer at add time", async () => {
    const composition = await services.visualCompositionService.createComposition(
      {
        projectId: otherProjectId,
        userId: other.user.id,
        name: "Other composition",
      },
    );

    // The stored asset belongs to the owner's project. Adding the layer resolves
    // the ref against the other project, where it does not exist, so the layer
    // is refused rather than stored with a dangling reference.
    await expect(
      services.visualLayerService.addLayer({
        projectId: otherProjectId,
        compositionId: composition.id,
        userId: other.user.id,
        type: "MEDIA",
        assetRef,
      }),
    ).rejects.toMatchObject({ status: 404 });
  });
});
